### PR TITLE
Made ability cooldown only apply when calling CommitAbilityCostAndCooldown()...

### PR DESCRIPTION
**Pull request by LeoFabre**
... or CommitAbilityCooldown() (fixes issue #25)

### CODE REVIEW

**Comment by LeoFabre** [comment]
I've implemented a CommitAbilityCooldown() method and a CommitAbilityCostAndCooldown() which are respectively alternatives to GAS' CommitCooldown() and CommitAbility(), the latter with a longer name for the sake of clarity and to respect how CommitAbilityCost() is named.

This introduces a breaking change, though : All abilities will now **_NOT_** apply their cooldown if none of the new methods are called.

This is default GAS behavior, but if you want me to add a bApplyCooldownAtAbilityBegin property that is true by default, let me know.

**Comment by LeoFabre** [comment]
Actually I think it's best to add that boolean. Let me fix that real quick.
Also, I had to redo my fork and forgot to remove the SetCooldownForAbility in BeginAbility, so I'll just wrap it in an if() and it'll be all good.

**Comment by LeoFabre** [comment]
Done !
Let me know if you don't like it.

**Comment by reznok** [comment]
LGTM. I would like to eventually handle cooldowns similar to GAS and do them as Effects so that they can be properly synced in the case of mispredictions, but this design wouldn't change. That would just change the float timer part of it. Thanks!

**Review by reznok — APPROVED** [review]

**Comment by LeoFabre** [comment]
You're very welcome 👌

**Pull request merged**
